---
ci_config: &ci_config
  - ".github/workflows/ci.yml"
  - ".github/file-filters.yml"

coverage_config: &coverage_config
  - "codecov.yml"

github_workflows: &github_workflows
  - ".github/workflows/*.yml"

development_files: &development_files
  - "development/**"
  - "tasks/**"

poetry_files: &poetry_files
  - "pyproject.toml"
  - "poetry.lock"

doc_files: &doc_files
  - "docs/**"

python_all: &python_all
  - "**/*.py"
  - *poetry_files
  - *ci_config
  - *coverage_config

yaml_all: &yaml_all
  - "**/*.{yml,yaml}"

markdown_all: &markdown_all
  - "**/*.{md,mdx}"

documentation_all:
  - *development_files
  - *doc_files
  - *markdown_all
