---
name: 🐛 Bug Report
description: Create a report to help us improve the python SDK for Infrahub
title: 'bug: '
labels: ["type/bug"]
body:
  - type: dropdown
    attributes:
      label: Component
      description: Please indicate which component(s) this feature is associated with (leave blanc if unknown)
      multiple: true
      options:
        - Python SDK
        - infrahubctl
        - Not Sure
  - type: input
    attributes:
      label: Infrahub SDK version
      description: Infrahub version (e.g. 0.13.2)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A clear description of what the bug is and how it manifests.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Please explain the steps required to duplicate this issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: |
        List any other information that is relevant to your request.
        Stack traces, related issues, suggestions on how to implement, Stack Overflow links, forum links, etc.
